// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:expenses_tracker/src/features/budget/domain/models/budget_model.dart';
import 'package:expenses_tracker/src/features/expenses/domain/models/expense_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetAdapter());
    registerAdapter(ExpenseAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetAdapter());
    registerAdapter(ExpenseAdapter());
  }
}
